version: '3'
services:

    # PHP Service
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: php:8.1.5-fpm
        container_name: yord_php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - backend

    # Nginx Service
    webserver:
        depends_on:
            - db
        links:
            - db
        image: nginx:alpine
        container_name: yord_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - backend

    # MySQL Service
    db:
        image: mysql:5.7.24
        container_name: yord_mysql
        command: "--default-authentication-plugin=mysql_native_password"
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: yord
            MYSQL_PASSWORD: yord
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - my-db:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - backend

    # PhpMyAdmin Service
    phpmyadmin:
        depends_on:
            - db
        links:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: yord_phpmyadmin
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: password
        networks:
            - backend

networks:
    backend:

volumes:
    my-db: